{
 "title": "Spring Boot 2.1 System Monitor",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Heaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics Threads/Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Config Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jetty_threads_config_min{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Min threads"
      }
     ]
    },
    {
     "title": "HTTP Codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
       "legendFormat": "5xx - Server Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"4..\"}[1m]))",
       "legendFormat": "4xx - Client Errors"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"2..\"}[1m]))",
       "legendFormat": "2xx - Success"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"3..\"}[1m]))",
       "legendFormat": "3xx - Redirections"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jetty_threads_config_max{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Max threads"
      }
     ]
    },
    {
     "title": "Requests/second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
       "legendFormat": "Requests per second"
      }
     ]
    },
    {
     "title": "Requests duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "TOP 10",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jetty_threads_current{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "jetty_threads_busy{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Busy thread"
      },
      {
       "expr": "jetty_threads_idle{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Idle threads"
      },
      {
       "expr": "jetty_threads_jobs{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Jobs  threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}