spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/migration/master.yml
    enabled: true

encryption:
  secret-key: ThisIsA32ByteSecretKeyForAES256! # Безопасность (PCI DSS). Если злоумышленник получит доступ к БД, он не увидит номера карт(маскировка).

validation:
  max-transfer-amount: 100000000
  max-balance: 1000000000

logging:
  level:
    com:
      example:
        bank:
          cards: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api # Общий endpoint для app.




  #Что нужно сделать:
  # + Указать настройки подключения к базе данных.
  # + Указать порт приложения.
  # - Настроить параметры безопасности и JWT.
  # - Включить Swagger UI.